services:
    redis:
        image: redis
        ports:
            - "6379:6379"

    mongo:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: mysecurepassword
        volumes:
            - mongodata:/data/db

    worker:
        build:
            context: .
            dockerfile: Dockerfile.worker
        depends_on:
            - redis
            - mongo
        environment:
            REDIS_URL: redis://redis:6379/0
            MONGO_URL: mongodb://root:mysecurepassword@mongo:27017/
        volumes:
            - /app/.venv
            - ".:/app"

    api:
        build:
            context: .
            dockerfile: Dockerfile.api
        ports:
            - "8000:8000"
        depends_on:
            - mongo
        environment:
            MONGO_URL: mongodb://root:mysecurepassword@mongo:27017/
        volumes:
            - ".:/app"

volumes:
    mongodata:
